version: "3.7"

services:
  sqlDatabase:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    volumes:
      - ./services/db:/var/lib/mysql
    networks:
        connector:
            ipv4_address: 192.168.111.9

  apis:
    build:
      context: ./services/apis
      dockerfile: dev-Dockerfile
    expose:
      - 8080
    working_dir: /app
    depends_on: 
      - sqlDatabase
    volumes:
      - ./services/apis:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8080 --reload
    networks:
        connector:
            ipv4_address: 192.168.111.10

  frontend:
    build:
      context: ./services/frontend
      dockerfile: Dockerfile
    expose:
      - 5000
    working_dir: /app
    volumes:
      - ./services/frontend:/app
    command: python3 -m flask --debug run --host=0.0.0.0
    depends_on:
      - apis
    networks:
      connector:
        ipv4_address: 192.168.111.11

  nginx:
      build:
        context: ./services/nginx
      restart: always
      ports:
        - 80:80
      depends_on:
        - frontend
      networks:
        connector:
            ipv4_address: 192.168.111.12

networks:
  connector:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.111.0/24